# Generated by Django 5.2.5 on 2025-09-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('type', models.CharField(max_length=20, verbose_name='Вид')),
                ('color', models.CharField(max_length=20, verbose_name='Колір')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('zone', models.IntegerField(verbose_name='Зона')),
            ],
        ),
    ]
