# Generated by Django 5.2.5 on 2025-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('registration_date', models.DateField(verbose_name='Дата реєстрації')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
            ],
        ),
    ]
