# Generated by Django 5.2.5 on 2025-09-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
